require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.mason_lsp"
require "user.telescope"
require "user.autopairs"
require "user.comment"
require "user.alpha"
require "user.autocommands"
require "user.colorizer"
require "user.lualine"
require "user.vimtex"
require 'user.lualine'
require 'user.harpoon'
require 'user.undotree'
require 'user.vimwiki'
require 'user.ultisnips'
require 'user.quickscope'
require "user.copilot"
require 'user.gitsigns'
require "user.todo"
require 'user.treesitter'
require "user.bufferline"
require "user.project"
require "user.lsp"
require "user.chatgpt"
require "user.devcons"
require "user.markdownprev"
require "user.indentline"
require 'user.nvim-tree'
require "user.zen"
require "user.toggleterm"
